all :

fork :
	rm -rf fork
	gcc fork.c -o fork

zombie :
	rm -rf zombie
	gcc zombie.c -o zombie

wait :
	rm -rf wait
	gcc wait.c -o wait

waitpid :
	rm -rf waitpid
	gcc waitpid.c -o waitpid

signal :
	rm -rf signal
	gcc signal.c -o signal

sigaction:
	rm -rf sigaction
	gcc sigaction.c -o sigaction

move_zombie:
	rm -rf move_zombie
	gcc move_zombie.c -o move_zombie