all :

fork :
	rm -rf fork
	gcc fork.c -o fork

zombie :
	rm -rf zombie
	gcc zombie.c -o zombie

wait :
	rm -rf wait
	gcc wait.c -o wait

waitpid :
	rm -rf waitpid
	gcc waitpid.c -o waitpid

signal :
	rm -rf signal
	gcc signal.c -o signal

sigaction:
	rm -rf sigaction
	gcc sigaction.c -o sigaction

remove_zombie:
	rm -rf remove_zombie
	gcc remove_zombie.c -o remove_zombie

multi_echo_serv:
	rm -rf multi_echo_serv
	gcc multi_echo_serv.c -o multi_echo_serv